#!/bin/bash

#
# Spit out a big unread count to test proper thousand grouping.
#

cleanup()
{
   trap - 0 1 2 3 15 # clear the trap

   CHILDREN_PIDS="$(jobs -p)"
   if [ -n "$CHILDREN_PIDS" ] ; then
      kill -1 $CHILDREN_PIDS > /dev/null 2>&1
   fi
}

log_msg()
{
   echo "$(date '+%F %X') - $@"
}

trap 'cleanup; exit 0' 0 1 2 3 15

log_msg "MUA is up"

TOTAL_COUNT=89433
log_msg "Unread count = $TOTAL_COUNT"

sleep infinity

exit 0
