#!/bin/bash

#
# This script will cause the three icons to infinitely cycle every
# N seconds:
#
#    0 unread messages => 1..N unread messages => non-integer
#           ^                                         v
#           |                                         |
#           +-----------------------------------------+
#
# Good for troubleshooting, icon development, etc.
#

cleanup()
{
   trap - 0 1 2 3 15 # clear the trap

   CHILDREN_PIDS="$(jobs -p)"
   if [ -n "$CHILDREN_PIDS" ] ; then
      kill -1 $CHILDREN_PIDS > /dev/null 2>&1
   fi
}

log_msg()
{
   echo "$(date '+%F %X') - $@"
}

trap 'cleanup; exit 0' 0 1 2 3 15

#
# Index into the sleep array
#
log_msg "Cycle through the different icons."
log_msg "A non-integer is considered an error."
log_msg ""

SLEEP=4

log_msg "MUA is up"
sleep 0.1

while [ 1 ] ; do
   log_msg "Unread count = 0"
   sleep $SLEEP

   log_msg "Unread count = $((1 + $RANDOM % 1000))"
   sleep $SLEEP

   RANDOM_STRING=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '')
   log_msg "Unread count = $RANDOM_STRING"
   sleep $SLEEP

   log_msg "MUA is down"
   sleep $SLEEP

   log_msg "MUA is up" # largely a no-op.  In practice, it is immediately followed with a count
   sleep 0.1
done

exit 0
