#!/bin/bash

#
# Simulate death of the process.  Poor thing.
#

cleanup()
{
   trap - 0 1 2 3 15 # clear the trap

   CHILDREN_PIDS="$(jobs -p)"
   if [ -n "$CHILDREN_PIDS" ] ; then
      kill -1 $CHILDREN_PIDS > /dev/null 2>&1
   fi
}

log_msg()
{
   echo "$(date '+%F %X') - $@"
}

trap 'cleanup; exit 0' 0 1 2 3 15

log_msg "MUA is up"

#
# Index into the sleep array
#
log_msg "Cycle through the different icons."
log_msg "A non-integer is considered an error."
log_msg ""
TOTAL_COUNT=0
log_msg "Unread count = $TOTAL_COUNT"

sleep 8

log_msg "Terminating ..."

exit 0
